apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: agents
  annotations:
    github.com/project-slug: rohitratannagar/agents
spec:
  type: other
  lifecycle: unknown
  owner: user:default/rohitratannagar
